# Generated by Django 5.1.3 on 2024-11-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jboard', '0002_jobposting_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
